### ISSUE TITLE
can't download php-api-client with composer (following the documentation instructions)

### ISSUE THREAD

**Issue by fotonmoton** [akeneo/php-api-client#68]
when I run:
`composer require akeneo/api-php-client php-http/guzzle6-adapter`

I get:
`[InvalidArgumentException]                                                                         
  Could not find package akeneo/api-php-client at any version for your minimum-stability (stable).   
  Check the package spelling or your minimum-stability `

php -v:
`PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans`

composer -V:
`Composer version 1.4.2 2017-05-17 08:17:52`

**UPDATE**

Now I can install client with composer if specific version is set:

`composer require  akeneo/api-php-client:1.0.0-beta1 php-http/guzzle6-adapter`

**Comment by ahocquard** [comment]
Hello,

This is because it's a beta, so it's not a version considered stable by composer (default minimum-stability is `stable`).
You have to specify `beta` as the minimum stability constraint in your composer.

https://getcomposer.org/doc/04-schema.md#minimum-stability

You can do it per dependency as well: https://getcomposer.org/doc/04-schema.md#package-links

We will update the documentation.

Regards,
Alexandre

**Comment by fotonmoton** [comment]
@ahocquard thanks, doesn't know that.
